version: '2'
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - "127.0.0.1:5433:5432"
  client:
    build:
      context: ./client
    depends_on:
      - postgres
    tty: true
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
    volumes:
      - ./data:/data
      - ./client/queries:/home/queries
    links: [postgres]
